#!/usr/bin/env python3
"""
Single source of truth for course readings.

Readings live in ONE place: `activities-manifest.json` (which also drives the
website). This script propagates them so nothing drifts:

  1. Regenerates `planning/readings.md` (human-readable master list).
  2. Injects/updates a "Reading" section in each activity's `instructions.md`
     (between <!-- READINGS:START --> / <!-- READINGS:END --> markers).

The website reads `activities-manifest.json` directly, so it's always current.

Usage:
    python3 scripts/sync_readings.py          # write changes
    python3 scripts/sync_readings.py --check   # exit 1 if anything is out of date

Run this whenever you edit readings in activities-manifest.json.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "activities-manifest.json")
READINGS_MD = os.path.join(ROOT, "planning", "readings.md")

START = "<!-- READINGS:START (generated by scripts/sync_readings.py — edit activities-manifest.json instead) -->"
END = "<!-- READINGS:END -->"

ROLE_LABELS = {
    "primary": "Primary",
    "reference": "Reference",
    "pair": "Pair",
    "optional": "Optional",
}
ROLE_ORDER = ["primary", "reference", "pair", "optional"]
TAG_MARK = {"provided": "🟢", "syllabus": "🔵", "proposed": "🟡"}


def reading_line(r):
    label = ROLE_LABELS.get(r.get("role", "optional"), "Optional")
    mark = TAG_MARK.get(r.get("tag", ""), "")
    cite = r["cite"].strip()
    url = r.get("url", "").strip()
    body = f"[{cite}]({url})" if url else cite
    prefix = f"**{label}**"
    if mark:
        prefix += f" {mark}"
    return f"- {prefix} — {body}"


def sorted_readings(readings):
    return sorted(readings, key=lambda r: ROLE_ORDER.index(r.get("role", "optional"))
                  if r.get("role", "optional") in ROLE_ORDER else 99)


def build_readings_md(manifest):
    out = []
    out.append("# Course Readings")
    out.append("")
    out.append("> **Generated file — do not edit by hand.** Source of truth is "
               "`activities-manifest.json`. Edit readings there, then run "
               "`python3 scripts/sync_readings.py`.")
    out.append("")
    legend = manifest.get("readingLegend", {})
    marks = "  ·  ".join(f"{TAG_MARK[k]} {v}" for k, v in
                         [("provided", legend.get("provided", "instructor-suggested")),
                          ("syllabus", legend.get("syllabus", "in syllabus")),
                          ("proposed", legend.get("proposed", "proposed addition"))])
    out.append(f"Legend: {marks}. Thursdays are project days (no new reading).")
    out.append("")
    out.append("**Roles:** **Primary** = required reading before class; "
               "Reference / Pair / Optional = recommended or background, read as time and "
               "the activity's intensity allow.")
    out.append("")
    for week in manifest["weeks"]:
        out.append(f"## {week['label']} — {week['theme']}")
        out.append("")
        for act in week["activities"]:
            out.append(f"### {act['date']} — {act['title']}")
            readings = sorted_readings(act.get("readings", []))
            if not readings:
                out.append("- _No reading assigned yet._")
            for r in readings:
                out.append(reading_line(r))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def build_instructions_block(act, rel_readings_path):
    lines = [START, "", "## 📖 Reading", ""]
    readings = sorted_readings(act.get("readings", []))
    if not readings:
        lines.append("- _No reading assigned yet._")
    for r in readings:
        lines.append(reading_line(r))
    lines.append("")
    lines.append(f"**Full course reading list:** [readings.md]({rel_readings_path})")
    lines.append(END)
    return "\n".join(lines)


def inject(text, block):
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(text):
        return pattern.sub(lambda _: block, text)
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return text + sep + "\n" + block + "\n"


def main():
    check = "--check" in sys.argv
    manifest = json.load(open(MANIFEST, encoding="utf-8"))

    stale = []

    # 1. readings.md
    new_md = build_readings_md(manifest)
    old_md = open(READINGS_MD, encoding="utf-8").read() if os.path.exists(READINGS_MD) else ""
    if new_md != old_md:
        stale.append("planning/readings.md")
        if not check:
            open(READINGS_MD, "w", encoding="utf-8").write(new_md)

    # 2. each activity instructions.md
    for week in manifest["weeks"]:
        for act in week["activities"]:
            path = os.path.join(ROOT, week["id"], act["folder"], "instructions.md")
            if not os.path.exists(path):
                print(f"  ! missing {os.path.relpath(path, ROOT)} — skipped")
                continue
            text = open(path, encoding="utf-8").read()
            block = build_instructions_block(act, "../../planning/readings.md")
            new_text = inject(text, block)
            if new_text != text:
                stale.append(os.path.relpath(path, ROOT))
                if not check:
                    open(path, "w", encoding="utf-8").write(new_text)

    if check:
        if stale:
            print("Out of date (run scripts/sync_readings.py):")
            for s in stale:
                print(f"  - {s}")
            sys.exit(1)
        print("✓ readings in sync")
    else:
        if stale:
            print("Updated:")
            for s in stale:
                print(f"  - {s}")
        else:
            print("✓ already in sync")


if __name__ == "__main__":
    main()
